# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

user1 = User.create({username: "amitpamin", password_digest: "asdfasdfasdfasdf", email: "asdfasdf", session_token: "Afasdasdf"})
user2 = User.create({username: "firbran", password_digest: "asdfasdfasdfasdf", email: "asdfddddasdf", session_token: "Afasdsssasdf"})
user3 = User.create({username: "McDonald McGee", password_digest: "asdfasdfasdfasdf", email: "asdfasddddf", session_token: "Afasdaaaasdf"})
user4 = User.create({username: "SweePee", password_digest: "asdfasdfasdfasdf", email: "asdfaaaasdf", session_token: "Afwwwwasdasdf"})


work1 = Work.create({name: "Harry Potter and the Methods of Rationality", author: " Eliezer Yudkowsky", link: "http://hpmor.com/", description: "Petunia married a biochemist, and Harry grew up reading science and science fiction. Then came the Hogwarts letter, and a world of intriguing new possibilities to exploit. And new friends, like Hermione Granger, and Professor McGonagall, and Professor Quirrell...", length: "Epic"})
work2 = Work.create({name: "The World of Null-A", author: "A. E. Van Vogt", link: "http://www.amazon.com/The-World-Null-A-Van-Vogt/dp/0765300974", description: "It is the year 2650 and Earth has become a world of non-Aristotelianism, or Null-A. This is the story of Gilbert Gosseyn, who lives in that future world where the Games Machine, made up of twenty-five thousand electronic brains, sets the course of people's lives. Gosseyn isn't even sure of his own identity, but realizes he has some remarkable abilities and sets out to use them to discover who has made him a pawn in an interstellar plot.", length: "Medium"})
work3 = Work.create({name: "The Players Of Null-A", author: "A. E. Van Vogt", link: "http://www.amazon.com/The-Players-Null-A-Van-Vogt/dp/0898041546", description: "In this sequel to World of Null-A, Gilbert Gosseyn must learn to use both hisbrains and function in various bodies in order to save the universe from Enrothe Red.", length: "Medium"})
work4 = Work.create({name: "Three Worlds Collide", author: "Eliezer Yudkowsky", link: "http://lesswrong.com/lw/y4/three_worlds_collide_08/", description: "This is a story of an impossible outcome, where AI never worked, molecular nanotechnology never worked, biotechnology only sort-of worked; and yet somehow humanity not only survived, but discovered a way to travel Faster-Than-Light:  The past's Future. Ships travel through the Alderson starlines, wormholes that appear near stars.  The starline network is dense and unpredictable: more than a billion starlines lead away from Sol, but every world explored is so far away as to be outside the range of Earth's telescopes.  Most colony worlds are located only a single jump away from Earth, which remains the center of the human universe. From the colony system Huygens, the crew of the Giant Science Vessel Impossible Possible World have set out to investigate a starline that flared up with an unprecedented flux of Alderson force before subsiding.  Arriving, the Impossible discovers the sparkling debris of a recent nova - and -", length: "Short"})
work5 = Work.create({name: "Luminosity", author: "Alicorn", link: "http://luminous.elcenia.com/", description: " Luminosity is a work of fanfiction. It is set in the universe of Stephenie Meyer's novel Twilight (and its sequels and companion works). The first several sections of Luminosity are very similar to canon in terms of the events that occur, although aspects of Bella's character, and her internal monologue, differ strikingly. A few thousand words in, the plot is unrecognizeable. The history and character of the Twilight world are intact in Luminosity up to the point where the story begins, with one exception: Bella's a rational self-awareness-junkie with a penchant for writing down everything that crosses her mind in a notebook. She maintains many of the traits and dispositions of canon - and Luminosity is a Bella/Edward story - but she's a distinctly different character. Luminosity was inspired in part by Harry Potter and the Methods of Rationality, in which Harry is a scientifically minded and sharp-witted boy who was brought up by Petunia and her alternate-universe professor husband.", length: "Epic"})
work6 = Work.create({name: "Worm", author: "Wildbow", link: "https://parahumans.wordpress.com/", description: "An introverted teenage girl with an unconventional superpower, Taylor goes out in costume to find escape from a deeply unhappy and frustrated civilian life. Her first attempt at taking down a supervillain sees her mistaken for one, thrusting her into the midst of the local ‘cape’ scene’s politics, unwritten rules, and ambiguous morals. As she risks life and limb, Taylor faces the dilemma of having to do the wrong things for the right reasons.", length: "Epic"})
work7 = Work.create({name: "Weaver 9", author: "Thinker6", link: "https://www.fanfiction.net/s/10898446/1/Weaver-Nine", description: "Worm fanfiction. Taylor and Jack Slash are born in each other's places. Weaver is the infamous usurper of the Slaughterhouse Nine, while young Jacob Hebert forges his path through the underworld of Brockton Bay.", length: "Long"})
work8 = Work.create({name: "Friendship Is Optimal", author: "Iceman", link: "http://www.fimfiction.net/story/62074/friendship-is-optimal", description: "Hanna, the CEO of Hofvarpnir Studios, just won the contract to write the official My Little Pony MMO. Hanna has built an A.I. Princess Celestia and given her one basic drive: to satisfy everybody's values through friendship and ponies. Princess Celestia will satisfy your values through friendship and ponies, and it will be completely consensual.", length: "Medium"})
work9 = Work.create({name: "Pokemon: the Origin of Species", author: "daystar721", link: "https://www.fanfiction.net/s/9794740/1/Pokemon-The-Origin-of-Species", description: "Enter the world of Pokémon from a rational perspective. Instead of starting his journey in ignorance, Red has spent his years studying the creatures so central to his world... and he doesn't quite agree with all the information in his books. No time for rookie mistakes here: he's on a quest to discover the true nature of Pokémon, and maybe even find out where they really come from.", length: "Long"})
work10 = Work.create({name: "Rationalising Death", author: "Scientist's Thesis", link: "https://www.fanfiction.net/s/9380249/1/Rationalising-Death", description: "Death Note fanfiction. What if the mentioned super intelligence of Yagami Light and his antagonists wasn't just informed, but was actually true?", length: "Medium"})
work11 = Work.create({name: "Branches on the Tree of Time", author: "Alexander Wales", link: "https://www.fanfiction.net/s/9658524/1/Branches-on-the-Tree-of-Time", description: "Kyle Reese has traveled backwards in time, not to save Sarah Connor, but to help her rewrite the faulty utility function of Skynet. Together, it's possible that they might avert Judgment Day and save the world from nuclear Armageddon - and hopefully create a utopia ruled over by an AI god in the process. Fully completed. Diverges wildly from canon.", length: "Short"})
work12 = Work.create({name: "The Metropolitan Man", author: "Alexander Wales", link: "https://www.fanfiction.net/s/10360716/1/The-Metropolitan-Man", description: "The year is 1934, and Superman has arrived in Metropolis. Features Lex Luthor as the villain protagonist as he comes to grips with the arrival of an alien god. Occasional point-of-view chapters/sections featuring Lois Lane. Takes place outside any established comics continuity.", length: "Medium"})
work13 = Work.create({name: "A Bluer Shade of White", author: "Alexander Wales", link: "https://www.fanfiction.net/s/10327510/1/A-Bluer-Shade-of-White", description: "Six years after her coronation, Elsa rules over Arendelle, using the power of ice to improve the lives of her citizens.", length: "Short"})
work14 = Work.create({name: "The Last Christmas", author: "Alexander Wales", link: "https://www.fanfiction.net/s/9915682/1/The-Last-Christmas", description: "The mantle of Santa Claus has been passed down once again, this time to an industrial engineer who starts to get some dangerous ideas in his head about the true meaning of Christmas.", length: "Short"})

chapter1 = Chapter.create({work_id: 1, number: 80, link: "asdfsadf"});
chapter2 = Chapter.create({work_id: 1, number: 81, link: "asdfsadf"});
chapter3 = Chapter.create({work_id: 1, number: 82, link: "asdfsadf"});

rating1 = Rating.create({work_id: 1, user_id: 1, rating: 4})
rating2 = Rating.create({work_id: 1, user_id: 2, rating: 5})
rating3 = Rating.create({work_id: 1, user_id: 3, rating: 1})
rating4 = Rating.create({work_id: 1, user_id: 4, rating: 1})
rating5 = Rating.create({work_id: 2, user_id: 1, rating: 2})
rating6 = Rating.create({work_id: 2, user_id: 2, rating: 2})
rating7 = Rating.create({work_id: 2, user_id: 3, rating: 1})
rating8 = Rating.create({work_id: 2, user_id: 4, rating: 1})
rating9 = Rating.create({work_id: 3, user_id: 1, rating: 4})
rating10 = Rating.create({work_id: 3, user_id: 3, rating: 4})
rating11 = Rating.create({work_id: 3, user_id: 3, rating: 5})
rating12 = Rating.create({work_id: 3, user_id: 4, rating: 5})

rating13 = Rating.create({chapter_id: 1, user_id: 3, rating: 4})
rating14 = Rating.create({chapter_id: 2, user_id: 3, rating: 5})
rating15 = Rating.create({chapter_id: 3, user_id: 4, rating: 5})
# Rating.create({chapter_id: 1, user_id: 4, rating: 5})
